# Generated by Django 3.2.18 on 2023-04-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20230410_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courseID',
            new_name='pathwayID',
        ),
    ]
