# Generated by Django 3.2.18 on 2023-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_rename_courseid_student_pathwayid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='stuInfoCurrentLevel',
            field=models.IntegerField(default=1),
        ),
    ]
