# Generated by Django 3.2.18 on 2023-04-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_rename_interestimportantce_studentinterest_interestimportance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulelecturer',
            old_name='lectureID',
            new_name='lecturerID',
        ),
    ]
