# Generated by Django 3.2.18 on 2023-04-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_assessment_assessmentid'),
        ('database', '0009_auto_20230412_1527'),
    ]

    operations = [
    ]
