# Generated by Django 3.2.18 on 2023-04-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_student_studentcurrentsemester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentName',
        ),
    ]
