# Generated by Django 3.2.18 on 2023-03-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulecourse',
            old_name='courseID',
            new_name='courseRef',
        ),
        migrations.RenameField(
            model_name='modulecourse',
            old_name='moduleID',
            new_name='moduleRef',
        ),
    ]
