# Generated by Django 3.2.19 on 2023-10-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerModule',
        ),
    ]
