# Generated by Django 3.2.21 on 2023-10-05 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otp_totp', '0002_auto_20190420_0723'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessmentID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessmentWeight',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='moduleDescription',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='student',
            name='currentPathwayMark',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='studentmodule',
            name='stuModMark',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='studentmoduleassesment',
            name='assesmentMark',
            field=models.FloatField(default=100),
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('totpdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_totp.totpdevice')),
                ('associatedUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Authentication',
            },
            bases=('otp_totp.totpdevice',),
        ),
    ]
