# Generated by Django 3.2.21 on 2023-10-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_twofactorauth_associateduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
    ]
