# Generated by Django 3.2.22 on 2023-10-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_delete_twofactorauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModuleAssessment',
            fields=[
                ('studentModuleAssessmentID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('assessmentMark', models.FloatField(default=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentmoduleassesment',
            name='assessmentID',
        ),
        migrations.RemoveField(
            model_name='studentmoduleassesment',
            name='studentModuleID',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='lecturerModules',
            field=models.ManyToManyField(to='database.Module'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessmentID',
            field=models.CharField(auto_created=True, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ModuleLecturer',
        ),
        migrations.DeleteModel(
            name='StudentModuleAssesment',
        ),
        migrations.AddField(
            model_name='studentmoduleassessment',
            name='assessmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.assessment'),
        ),
        migrations.AddField(
            model_name='studentmoduleassessment',
            name='studentModuleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.studentmodule'),
        ),
    ]
