# Generated by Django 3.2.19 on 2023-11-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_career_careerid'),
        ('database', '0005_auto_20231019_1536'),
    ]

    operations = [
    ]
