# Generated by Django 3.2.18 on 2023-04-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_studentinfo_stuinfocurrentlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinterest',
            old_name='interestImportantce',
            new_name='interestImportance',
        ),
    ]
