# Generated by Django 3.2.18 on 2023-04-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_lectureid_modulelecturer_lecturerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessmentID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='StudentModuleAssesment',
            fields=[
                ('studentModuleAssesmentID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('assesmentMark', models.IntegerField(default=100)),
                ('assessmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.assessment')),
                ('studentModuleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.studentmodule')),
            ],
        ),
    ]
