# Generated by Django 3.2.18 on 2023-04-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_lectureid_modulelecturer_lecturerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessmentID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
