# Generated by Django 3.2.18 on 2023-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_merge_20230413_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentCurrentLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='studentName',
            field=models.CharField(default='temp', max_length=100),
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
