# Generated by Django 3.2.18 on 2023-04-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20230417_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentCurrentSemester',
            field=models.IntegerField(default=1),
        ),
    ]
